# Future plans

```{r setup_5, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

In this RMD file, my plans for the future skill I want to learn will be layed out. During DSFB2, 4 days (32 hours) have been given as free time, to perform our own research and practice into learning a new workflow/skill.

As my goal is to go into data sciences within microbiology, one way to spend this time is to learn further workflows within bacterial research. For example, There is more depth to be found in the identification of bacterial colonies by computers: https://towardsdatascience.com/recognition-and-counting-of-microorganisms-on-petri-dishes-53a499283dc8

Furthermore, I could also use this time to further study further workflows in microbiome research, and study what workflows are used when studying the microbiome.https://builtin.com/data-science/microbiome-research-data-science

Lastly, I could also spent this time starting my learning journey in Python. With this, I could both study automisation and, perhaps more importantly, start on studying how machine learning works. https://automatetheboringstuff.com/2e/chapter13/
